apiVersion: skaffold/v2beta23
kind: Config
build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/christian-kreuzberger-dtx/upper-case-service # Todo: Replace this with your image name
      docker:
        dockerfile: Dockerfile
        buildArgs:
          debugBuild: true
deploy:
  helm:
    flags:
      upgrade: ["--reuse-values", "--install"]
    releases:
      - name: upper-case-service
        namespace: keptn
        artifactOverrides:
          image: ghcr.io/christian-kreuzberger-dtx/upper-case-service # Todo: Replace this with your image name
        imageStrategy:
          helm: { }
        overrides:
          distributor:
            image:
              tag: 0.12.2
          resources:
            limits:
              memory: 512Mi
        chartPath: chart
